### PR TITLE
add support for slog WithAttrs

### PR DESCRIPTION
**Pull request by DimaGolomozy**

### CODE REVIEW

**Review by daidokoro — APPROVED** [review]
Thanks @DimaGolomozy 

LGTM

**Review by daidokoro — DISMISSED** [review]
lgtm

**Comment by DimaGolomozy** [comment]
signed to commit

**Comment by DimaGolomozy** [comment]
@daidokoro i've finished with the PR :)

**Review by daidokoro — APPROVED** [review]
LGTM

@DimaGolomozy ,  there are still [some commits that are not signed](https://github.com/coralogix/go-coralogix-sdk/pull/19/commits). These are preventing the pipeline from allowing a merge.

**Pull request merged**
